### ISSUE TITLE
atentionare la programarea ATmega 8

### ISSUE THREAD

**Issue by alexjfy** [etc-sodtr/ATMega328-Project#3]
Buna ziua,

Atunci cand programez uC ATmega 8 (care opereaza transmisia prin SPI) primesc mesaj ca ceasul nu s-a setat. Imi puteti spune va rog frumos care este problema? Multumesc

![transmitator](https://cloud.githubusercontent.com/assets/11389563/21957229/d48f3ca2-da9a-11e6-97d9-b091bbd3c5e6.png)

**Comment by kcs** [comment]
e doar un warning că nu folosești ultima versiune de usbasp, aceasta ar permite setarea unei viteze mai mari la SPI pentru programare ce reduce un pic timpul necesar programării (mai ales la un program mare care umple de exemplu un ATmega128)
în rest nu afectează cu nimic funcționarea

**Comment by alexjfy** [comment]
multumesc
