### ISSUE TITLE
nefunctionare procese in sincron

### ISSUE THREAD

**Issue by alexjfy** [etc-sodtr/ATMega328-Project#4]
Buna ziua, la implementarea existenta in folderul **receptor** procesele nu se mai executa. Ceea ce mai vad eu (excluzand SPI-ul pe care nu l-am probat sa vad daca functioneaza sau nu) este ca ledul de pe PC0 se aprinde o data scurt si ledul de pe PD4 (pe PD5 nu am pus led sa vad ce se intampla) sta tot timpul aprins.
M-ati putea ajuta cu o solutie, va rog?

**Comment by kcs** [comment]
nu înțeleg la care proiect te referi, și ce înseamnă PC0 și PD4
în schimb uitându-mă în folderul `mutex cu SPI` la receptor am văzut un haos total, nici nu vreau să-mi închipui cum au ajuns acolo așa amestecate semafoare, secțiuni critice ce conțin apeluri blocante, folosirea mutecșilor fără eliberare etc...
poate cumva ai scăpat vreo pagină la scrollare sau ai copiat din greșeală niște secțiuni de cod peste altul, așa că cel mai bine ar fi să faci revizuiești complet ce e acolo și să faci o curățenie, renunțând la codul care nu mai e folosit
de aceea folosești git să ai tot istoricul dezvoltării codului, nu mai trebuie să menții codul vechi tot adăugând noi secvențe, ci pur și simplu scrie peste, șterge ce nu e folosit că după un anumit moment de timp nu se mai înțelege nimic
și apropo poate ar fi bine să începi prin desenarea funcționalității dorite, trăgând liniile paralele cu ce trebuie să se întâmple în paralel și unde e nevoie de sincronizare, și doar acolo să folosești sincronizarea (și dedicat cazului particular)

**Comment by alexjfy** [comment]
Am facut schema de care mi-ati zis si, uitandu-ma si in codul lui @f-dumi , mi-am aranjat si codul si acum ruleaza toate procesele in paralel (mai putin SPI-ul pe care nu am reusit sa il verific) si functioneaza si excluderea muttuala folosita pentru citirea valorii potentiometrului

. La o prima verificare SPI-ul nu a facut nimic. Am incercat sa depanez mai adanc rutina de SPI(ar trebui sa clipeasca un led in functie de datele primite) dar, intre timp (nu stiu exact cum am reusit, cred ca am alimentat din greseala pinul de GND) am ars microcontrollerul ATmega 8. Acum, cand il alimentez se aprinde pe placuta doar un led care este legat direct intre VCC si masa . Daca incerc sa programez uC-ul primesc mesaj : 
![eroare](https://cloud.githubusercontent.com/assets/11389563/21963937/4db897da-db4b-11e6-8755-111151e46a6f.png)

**Comment by alexjfy** [comment]
Si ar mai fi o problema. In fisierele pe care le import pt Atmega 8, am urmatorul cod:

in main.c
	`//Timer aktivieren ATMEGA8
	#if defined(__AVR_ATmega8__)
	TCCR0 |= ( (1<<CS02) | (1<<CS00));		//Prescaler auf 1024 ATMEGA8
	TIMSK |= ( (1<<TOIE0));					//enable TOVF ATMEGA8
	#endif // __AVR_ATmega8__
	
	//Timer aktivieren ATMEGA88A
	#if defined(__AVR_ATmega88A__)
	TCCR0B |= ( (1<<CS02) | (1<<CS00));
	TIMSK0 |= ( (1<<TOIE0));
	#endif // __AVR_ATmega88A__`

	in wl_module.c

	`#if defined(__AVR_ATmega8__)
    // Initialize external interrupt 0 (PD2)
    MCUCR = ((1<<ISC11)|(0<<ISC10)|(1<<ISC01)|(0<<ISC00));	// Set external interupt on falling edge
    GICR  = ((0<<INT1)|(1<<INT0));							// Activate INT0
#endif // __AVR_ATmega8__

#if defined(__AVR_ATmega88A__)
	EICRA = ((1<<ISC11)|(0<<ISC10)|(1<<ISC01)|(0<<ISC00));	// Set external interupt on falling edge for INT0 and INT1
	EIMSK  = ((0<<INT1)|(1<<INT0));							// Activate INT0
#endif // __AVR_ATmega88A__

#if defined(__AVR_ATmega168__)
    // Initialize external interrupt on port PD6 (PCINT22)
    DDRB &= ~(1<<PD6);
    PCMSK2 = (1<<PCINT22);
    PCICR  = (1<<PCIE2);
#endif // __AVR_ATmega168__`

Nu stiu unde este setata variabila care defineste uC-ul meu sau cum determina compilatorul de uC am. Mai sus este cod extras din fisierele pentru ATmega 8. Pt ATmega 328 am inlocuit 

`#if defined(__AVR_ATmega168__)
    // Initialize external interrupt on port PD6 (PCINT22)
    DDRB &= ~(1<<PD6);
    PCMSK2 = (1<<PCINT22);
    PCICR  = (1<<PCIE2);
#endif // __AVR_ATmega168__`
    
cu

`#if defined(__AVR_ATmega328__)
    // Initialize external interrupt on port PD6 (PCINT22)
    DDRB &= ~(1<<PD6);
    PCMSK2 = (1<<PCINT22);
    PCICR  = (1<<PCIE2);
#endif // __AVR_ATmega328__`
    
deoarece am inteles ca aceste 168 si 328 au aceleasi intreruperi

**Comment by f-dumi** [comment]
@alexjfy legat de erorile din avrdude:
1. verifica ca ai toate conexiunile bune. Sa nu fie intrerupta vreuna din linii. Eu am patit-o cu linia de reset, nu facea contact bine si nu era resetat controller-ul calumea.
2. Sigur nu ai modificat vreun fuse bit? Daca ai dezacivat cumva fuse bit-ul de reset, atunci controller-ul nu mai poate fi programat (poti sa iei altul direct).
3. Verifica conexiunea controller-ului cu cristalul de quartz. Daca oscilatorul intern al microcontroller-ului nu functioneaza, acesta nu poate fi detectat de programator.

Altfel, daca suspectezi ca l-ai alimentat invers, in acest caz la alimentarea inversa se pot distruge diodele interne de protectie.
Odata alimentat corect, verifica ce curent consuma controller-ul. In timpul testului poti sa-l mentii fortat in reset legand linia de reset la GND. Astfel stii ca nu se ruleaza niciun program. Astfel curentul consumat de controller ar trebui sa fie de ordinul uA (pana in 1mA) din ce vad din foaia de catalog. Daca asa consuma sa zicem peste 10mA, ceva e in neregula. Poti sa-l schimbi.

**Comment by kcs** [comment]
pentru prima problema f-dumi deja a răspuns complet
pentru cea de a doua răspunsul scurt este că gcc definește automat acel macro cu numele procesorului selectat, așa că ai procedat corect
